### PR TITLE
Update mafia.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
! @charleso

### CODE REVIEW

**Comment by charleso** [comment]
Same error. I'd recommend try updating the master runner.

I'm confused though, how does this PR have the branches-8-0 build?

**Comment by tmcgilchrist** [comment]
Cause you added wildcards to the boris-git.toml file :-)

No idea about the runner, it's using the same version as other projects with 8.0 builds.

**Comment by charleso** [comment]
> Cause you added wildcards to the boris-git.toml file 

It only picks up builds in the boris file on the same commit. This branch/PR doesn't have any builds called "branches-8-0".

**Comment by charleso** [comment]
Ahh, sorry you haven't rebased. Makes sense nonw

**Pull request closed without merging**
